version: "2"

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=sikwel_db
      - POSTGRESQL_USERNAME=sikwel
      - POSTGRESQL_PASSWORD=secret#s1kw3lPW
    volumes:
      - postgres:/bitnami/postgresql/

  sikwel-data-engineering-trainee-project-environment:
    build:
      context: .
      dockerfile: ./Dockerfile.sikwel-environment
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/home/vscode/workspace:cached

    links:
      - postgresql

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
      
  job_daily:
    build:
      context: .
      dockerfile: ./Dockerfile.crontab
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    links:
     - postgresql
     
volumes:
  postgres:
    driver: local
